version: '3.8'

services:
  todosDB:
    image: postgres:15.3
    container_name: todos-db
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

# postgres-db:
#     image: postgres:15.3
#     restart: always
#     environment:
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_DB: ${DB_NAME}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#     volumes:
#       - ./postgres:/var/lib/postgresql/data
#     ports:
#       - 5433:5432
