import type { Metadata } from "next";
import "./globals.css";
import { roboto } from "@/config/fonts";
import { Providers } from "@/app/providers"; // Importa el proveedor de temas
import { SwitcherMini } from "@/components";
import AuthProvider from "@/auth/components/AuthProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html suppressHydrationWarning={true} lang="es">
        <body
          className={`${roboto.className} bg-gray-100 text-gray-900 dark:bg-gray-900 dark:text-gray-100 transition-all duration-300`}
        >
          <Providers>
            <SwitcherMini />
            {children}
          </Providers>
        </body>
      </html>
    </AuthProvider>
  );
}
